Algoritmo "exercicio3"

Var

  nome1, nome2 : caractere
  altura1, altura2 : real

Inicio

  escreva ("Primeiro nome: ")
    leia (nome1)
  
  escreva ("Respectiva altura: ")
    leia (altura1)
    
  escreva ("Segundo nome: ")
    leia (nome2)

  escreva ("Respectiva altura: ")
    leia (altura2)
    
       se ( altura1 > altura2 ) então
    escreva (nome1, " é mais alto(a) que ", nome2)

    senão
    escreva (nome2, " é mais alto(a) que ", nome1)

    fimse

    
Fimalgoritmo