Algoritmo "11"

Var
Nota1, nota2, nota3, media : real
Aluno : caractere

Inicio
 escreva (" Nome do aluno: ")
  leia(aluno)

 escreva (" Insira a primeira nota: ")
  leia(nota1)

 escreva (" Insira a segunda nota: ")
  leia(nota2)

 escreva (" Insira a terceira nota: ")
  leia(nota3)

   media <- (nota1 * 2 + nota2 * 3 + nota3 * 5) / 10

 escreva (" A média do aluno " , aluno , " é " , media)



Fimalgoritmo