Algoritmo "7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
temperatura : real


Inicio

   escreva ("Qual a temperatura ambiente?")
     leia (temperatura)
     
    se (temperatura >= 25 ) então
      escreva (" Esta muito quente!")
    
    senão
      escreva ("Está agradável!")

    Fimse

Fimalgoritmo